apiVersion: v1
kind: Secret
metadata:
  name: nova-secrets
  namespace: nova
type: Opaque
stringData:
  jwt-secret: "your-256-bit-secret-here-change-in-production"
  broker-code: "Kr000820"
  affiliate-id: "127146"
  telegram-token: "your-telegram-token-here"
  master-api-key: "your-master-key-here"
  master-api-secret: "your-master-secret-here"
